### ISSUE TITLE
Instead of using `scale` allow providing the unit

### ISSUE THREAD

**Issue by theomega** [tatarize/vpype-gcode#1]
It would be nice if you could provide the unit in which you want the gcode/output to be in instead of the scale.

vpype does this with its show command quite nicely:
https://github.com/abey79/vpype/blob/7592bf47fd525ca58e09ee92ae8c05082e9257a0/vpype_cli/show.py#L145

**Comment by tatarize** [comment]
Hm. Yeah, that wouldn't be too hard to calculate and would make a lot more since since the scale unit there is converting from 1/96 inch units into other units and ends up basically a weird number. Since the internal numbers in vpype won't really change.
